Run `acme-dns` container as user 0 on OpenShift 4
On OpenShift 4.11 the upstream acme-dns container (built from
https://github.com/joohoi/acme-dns/blob/6ba9360156b8658dbbd652eea100c11cc098b1f8/Dockerfile)
doesn't start anymore with SCC `restricted-v2` with error:

```
Error: container create failed: time="2022-12-13T13:06:02Z" level=error msg="runc create failed: unable to start container process: exec: \"./acme-dns\": stat ./acme-dns: permission denied"
```

This commit creates a dedicated service account for the acme-dns
deployment, and grants it permission to use SCC `anyuid`. Additionally
we set `runAsUser: 0` for the `acme-dns` container, so that it can
actually stat the binary.